### ISSUE TITLE
Get rid of `encoding` dependency

### ISSUE THREAD

**Issue by DDtKey** [Xiphoseer/serde-java-properties#3]
Hi there, 
Thanks for the serde compatible wrapper!

`encoding` crate is unmaintained: https://rustsec.org/advisories/RUSTSEC-2021-0153

Could we switch to [`encoding_rs`](https://crates.io/crates/encoding_rs/) instead?
E.g `java-properties` uses it https://crates.io/crates/java-properties/2.0.0/dependencies

**Comment by Xiphoseer** [comment]
Thanks for the heads up!

I updated the dependencies and released a new version. I prefer using `encoding_rs` anyway, have used it elsewhere in the past, so I welcome the change.

**Comment by DDtKey** [comment]
Thanks for the really fast update! 🙏 

It's now used by [Testcontainers for Rust](https://github.com/testcontainers/testcontainers-rs) and I caught this with `cargo audit`
